.Dd July 8, 2025
.Dt PLAKAR-LOGOUT 1
.Os
.Sh NAME
.Nm plakar-logout
.Nd Log out from Plakar services
.Sh SYNOPSIS
.Nm plakar logout
.Sh DESCRIPTION
The
.Nm plakar logout
command logs out an authenticated session with the Plakar platform.
.Sh EXAMPLES
Log out from the current session:
.Bd -literal -offset indent
$ plakar logout
.Ed
.Sh SEE ALSO
.Xr plakar 1 ,
.Xr plakar-login 1 ,
.Xr plakar-services 1
