.Dd August 6, 2025
.Dt PLAKAR-TOKEN 1
.Os
.Sh NAME
.Nm plakar-token
.Nd Manage Plakar tokens
.Sh SYNOPSIS
.Nm plakar token
.Op Cm create
.Sh DESCRIPTION
The
.Nm plakar token
command manages tokens used to authenticate to Plakar services.
Tokens are not currently usable and exist only for future features.
.Sh SUBCOMMANDS
.Bl -tag -width Ds
.It Cm create
Create a new token.
.El
.Sh SEE ALSO
.Xr plakar 1
