.Dd July 3, 2025
.Dt PLAKAR-SERVER 1
.Os
.Sh NAME
.Nm plakar-server
.Nd Start a Plakar server
.Sh SYNOPSIS
.Nm plakar server
.Op Fl allow-delete
.Op Fl listen Oo Ar host Ns Oc : Ns Ar port
.Sh DESCRIPTION
The
.Nm plakar server
command starts a Plakar server instance at the provided
.Ar address ,
allowing remote interaction with a Plakar repository over a network.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl allow-delete
Enable delete operations.
By default, delete operations are disabled to prevent accidental data
loss.
.It Fl listen Oo Ar host Ns Oc : Ns Ar port
The
.Ar host
and
.Ar port
where to listen to, separated by a colon.
The host name is optional, and defaults to all available addresses.
If
.Fl listen
is not provided, the server defaults to listen on localhost at port 9876.
.El
.Sh EXAMPLES
Start a plakar server on the local store:
.Bd -literal -offset indent
$ plakar server
.Ed
.Pp
Start a plakar server on a remote store:
.Bd -literal -offset indent
$ plakar at sftp://example.org server
.Ed
.Pp
Start a server on a specific address and port:
.Bd -literal -offset indent
$ plakar server -listen 127.0.0.1:12345
.Ed
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr plakar 1
.Sh CAVEATS
When a host name is provided,
.Nm plakar server
uses only one of the IP addresses it resolves to,
preferably IPv4 .
